# Generated by Django 5.0.6 on 2024-06-05 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_friends'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'ordering': ['sender', 'receiver'], 'verbose_name': 'Friend Request', 'verbose_name_plural': 'Friend Requests'},
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('sender', 'receiver')},
        ),
        migrations.AlterModelTable(
            name='friendrequest',
            table='friend_requests',
        ),
    ]
