---
name: Checks

on:
  push:
    branches:
      - main

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up .env file
        run: |
          echo SECRET_KEY=${{ secrets.SECRET_KEY }} > .env
          echo DEBUG=${{ secrets.DEBUG }} >> .env
          echo DEV_DB_HOST=${{ secrets.DEV_DB_HOST }} >> .env
          echo DEV_DB_NAME=${{ secrets.DEV_DB_NAME }} >> .env
          echo DEV_DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }} >> .env
          echo DEV_DB_USER=${{ secrets.DEV_DB_USER }} >> .env
          echo MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} >> .env

      - name: Start services
        run: docker compose up -d

      - name: Test
        run: docker compose run --rm web sh -c "python manage.py wait_for_db && python manage.py makemigrations && python manage.py migrate && python manage.py test"

      - name: Lint
        run: docker compose run --rm web sh -c "flake8"

      - name: Stop services
        run: docker compose down